---

flavors:
  teal:
    arches:
      x86_64:
        local_runner: false
        pipeline: "Examples"
        push_cache: false
        publishing_pipeline: false
        publish_cloud: false
        publish_toolchain: false
        skip_build: true
        luet_script_override: ""
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: true
        flavor: "teal"
        skip_tests_flavor: ["teal","green","blue","orange"]
        skip_images_flavor: ["teal","green", "blue","orange"]
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
        release_flavor: []
        luet_override: ""
        build_examples_dir: ["cos-official", "scratch", "standard"]
        arch: "x86_64"

        on:
          push:
            branches: [ "master" ]
          pull_request:
            paths:
              - 'conf/**'
              - 'packages/**'
              - 'make/**'
              - '.github/**'
              - 'Makefile'
              - 'tests/**'
              - 'examples/**'