---

flavors:
  teal:
    arches:
      x86_64:
        &x86_64
        local_runner: false
        runs_on: "ubuntu-latest"
        push_cache: true
        skip_build: false
        skip_docker_build: true
        pipeline: "main"
        publishing_pipeline: true
        publish_toolchain: true
        luet_override: ""
        luet_script_override: ""
        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "teal"
        skip_tests_flavor: ["blue","orange", "green"]
        skip_images_flavor: ["blue","orange", "green"]
        build_image_qemu: true
        run_installer_test: true
        run_tests:
          squashfs:
            - "test-recovery1"
            - "test-recovery2"
            - "test-recovery3"
            - "test-recovery4"
          nonsquashfs:
            - "test-hooks"
            - "test-smoke"
            - "test-fallback"
            - "test-recovery1"
            - "test-recovery2"
            - "test-recovery3"
            - "test-recovery4"
            - "test-upgrades-images-signed"
            - "test-upgrades-images-unsigned"
            - "test-upgrades-local"
            - "test-deploys-images-recovery"
        release_flavor: []
        arch: "x86_64"
        on:
          push:
            branches: ["main"]
        slack_on_failure: true
      arm64:
        &arm64
        local_runner: true
        runs_on: [ "self-hosted", "arm64" ]
        push_cache: true
        skip_build: false
        skip_docker_build: true
        luet_override: ""
        luet_script_override: ""
        pipeline: "main"
        publishing_pipeline: true
        publish_toolchain: false
        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        run_tests:
          squashfs:
            - "test-recovery1"
            - "test-recovery2"
            - "test-recovery3"
            - "test-recovery4"
          nonsquashfs:
            - "test-smoke"
            - "test-upgrades-images-unsigned"
        flavor: "teal"
        skip_tests_flavor: [ "blue","orange", "green"]
        skip_images_flavor: [ "blue","orange", "green" ]
        build_image_qemu: true
        release_flavor: [ ]
        arch: "arm64"
        on:
          push:
            branches: [ "main" ]
        slack_on_failure: true
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
        publish_toolchain: false
        slack_on_failure: false
      arm64:
        <<: *arm64
        flavor: "orange"
        publish_toolchain: false
        slack_on_failure: false
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
        publish_toolchain: false
        slack_on_failure: false
      arm64:
        <<: *arm64
        flavor: "blue"
        publish_toolchain: false
        slack_on_failure: false
  green:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "green"
        publish_toolchain: false
        slack_on_failure: false
      arm64:
        <<: *arm64
        flavor: "green"
        publish_toolchain: false
        slack_on_failure: false
