---

flavors:
  green:
    arches:
      x86_64:
        &x86_64
        local_runner: true
        runs_on: [ "self-hosted", "x64" ]
        push_cache: true
        skip_build: false
        skip_docker_build: true

        pipeline: "master"
        publishing_pipeline: true
        publish_cloud: false
        publish_toolchain: true
        luet_override: ""
        luet_script_override: ""
        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "green"
        skip_tests_flavor: ["blue","orange", "teal"]
        skip_images_flavor: ["blue","orange", "teal"]
        build_image_qemu: true
        build_image_vbox: true
        build_raw_image: true
        run_raw_image_test: true
        run_installer_test: true
        release_flavor: []
        arch: "x86_64"

        on:
          push:
            branches: ["master"]
      arm64:
        &arm64
        local_runner: true
        runs_on: [ "self-hosted", "arm64" ]
        push_cache: true
        skip_build: false
        skip_docker_build: true
        luet_override: ""
        luet_script_override: ""
        pipeline: "master"
        publishing_pipeline: true
        publish_cloud: false
        publish_toolchain: false

        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        run_tests: ["test-smoke", "test-upgrades-images-unsigned" ]
        flavor: "green"
        skip_tests_flavor: [ "blue","orange", "teal"]
        skip_images_flavor: [ "blue","orange", "teal" ]
        build_image_qemu: true
        build_image_vbox: false
        build_raw_image: true
        run_raw_image_test: false
        release_flavor: [ ]
        arch: "arm64"

        on:
          push:
            branches: [ "master" ]
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "orange"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "blue"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
  teal:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "teal"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "teal"
        publish_toolchain: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false