---


local_runner: false
push_cache: true
skip_build: false
skip_docker_build: false

pipeline: "master"
publishing_pipeline: true
publish_cloud: false

repository: "releases"
cache_repository: "build"
organization: "quay.io/costoolkit"
skip_tests: false
flavors: ["green", "blue", "orange"]
skip_tests_flavor: ["blue","orange"]
skip_images_flavor: ["blue","orange"]
release_flavor: []
arch: "amd64"

on: 
  push: 
    branches: ["master"]