---

flavors:
  teal:
    arches:
      x86_64:
        &x86_64
        local_runner: false
        push_cache: false
        skip_build: false
        skip_docker_build: false

        pipeline: "nightly"
        publishing_pipeline: false
        publish_cloud: false
        publish_toolchain: false
        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "teal"
        skip_tests_flavor: ["blue","orange", "green"]
        skip_images_flavor: ["blue","orange", "green"]
        build_image_qemu: true
        build_image_vbox: true
        build_raw_image: true
        luet_script_override: ""
        run_raw_image_test: true
        run_installer_test: true
        release_flavor: ["teal"]
        arch: "x86_64"
        luet_override: ""

        on:
          schedule:
            - cron:  '0 20 * * *'
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
  green:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "green"
