---

flavors:
  teal:
    arches:
      x86_64:
        &x86_64
        local_runner: false
        push_cache: false
        skip_build: false
        skip_docker_build: true
        pipeline: "nightly"
        publishing_pipeline: false
        publish_toolchain: false
        repository: "releases"
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "teal"
        skip_tests_flavor: ["blue","orange", "green"]
        skip_images_flavor: ["blue","orange", "green"]
        build_image_qemu: true
        build_raw_image: true
        luet_script_override: ""
        run_raw_image_test: true
        run_installer_test: true
        release_flavor: ["teal"]
        arch: "x86_64"
        luet_override: ""
        run_tests:
          squashfs:
            - "test-recovery"
          nonsquashfs:
            - "test-features"
            - "test-hooks"
            - "test-smoke"
            - "test-fallback"
            - "test-recovery"
            - "test-upgrades-images-signed"
            - "test-upgrades-images-unsigned"
            - "test-upgrades-local"
            - "test-deploys-images-recovery"
        on:
          schedule:
            - cron:  '0 20 * * *'
        slack_on_failure: true
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
        slack_on_failure: false
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
        slack_on_failure: false
  green:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "green"
        slack_on_failure: false
