---

flavors:
  teal:
    arches:
      x86_64:
        &x86_64
        local_runner: false
        pipeline: "docker"
        push_cache: false
        publishing_pipeline: false
        publish_toolchain: false
        publish_cloud: false
        skip_build: true
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: true
        flavor: "teal"
        skip_tests_flavor: ["green","blue","orange", "green"]
        skip_images_flavor: ["green","blue","orange", "green"]
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
        luet_override: ""
        luet_script_override: ""
        release_flavor: ["teal"]
        arch: "x86_64"
        on:
          pull_request:
            paths:
              - 'conf/**'
              - 'packages/**'
              - 'make/**'
              - '.github/**'
              - 'Makefile'
              - 'tests/**'
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
  green:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "green"