---

flavors:
  green:
    arches:
      x86_64:
        &x86_64
        local_runner: false
        pipeline: "Pull requests"
        push_cache: false
        publishing_pipeline: false
        publish_toolchain: false
        publish_cloud: false
        skip_build: false
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "green"
        skip_tests_flavor: [ "blue","orange" ]
        skip_images_flavor: [ "blue","orange" ]
        build_image_qemu: true
        build_image_vbox: true
        build_raw_image: true
        run_raw_image_test: true
        release_flavor: [ "green" ]
        arch: "x86_64"
        on:
          pull_request:
            paths:
              - 'conf/**'
              - 'packages/**'
              - 'make/**'
              - '.github/**'
              - 'Makefile'
              - 'tests/**'
      arm64:
        local_runner: true
        runs_on: [ "self-hosted", "arm64" ]
        pipeline: "Pull requests"
        push_cache: false
        publishing_pipeline: false
        publish_cloud: false
        publish_toolchain: false
        skip_build: false
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        run_tests: ["test-fallback"]
        flavor: "green"
        skip_tests_flavor: [ "blue","orange" ]
        skip_images_flavor: [ "blue","orange" ]
        skip_images_packer: true
        build_image_qemu: true
        build_image_vbox: false
        build_raw_image: true
        run_raw_image_test: false
        release_flavor: [ "green" ]
        arch: "arm64"
        # labels required for this job to run, list of labels. All will be required.
        labels: [ "arm64" ]

        on:
          pull_request:
            types: [ "labeled", "synchronize" ]  # synchronize means when the PR is updated
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false