# stages:
#    network:
#      - name: "Setup users"
#        authorized_keys:
#          root:
#          - github:...
#        ensure_entities:
#        - path: /etc/shadow
#          entity: |
#             kind: "shadow"
#             username: "root"
#             password: "$6$g9DDJRDNRS8MEzhH$w6Cn6PNzFnUVnatwRbNoLk6etanvAbcxUzfYlQcj6y/JLGq3Yrl7wXi6SkMzp1/tEM3NheMr5fH8.92NdiaB/0"
