name: Build cOS Pull requests - arm64
on: 
 pull_request:
   types:
     - labeled
     - synchronize
concurrency:
  group: ci-Pull requests - arm64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "arm64"
  build-green:
    runs-on: [self-hosted, arm64]
    if: contains(["mudler", "davidcassany", "itxaka", kkaempf", "cOS-cibot"], "${{ github.actor }}") || contains(github.event.pull_request.labels.*.name, 'safe to test')
    needs:
      - check-labels
    env:
      LUET_ARCH: arm64
      FLAVOR: green
      ARCH: arm64
      FINAL_REPO: quay.io/costoolkit/releases-green-arm64
      DOWNLOAD_METADATA: false
      PUSH_CACHE: false
      REPO_CACHE: quay.io/costoolkit/build-green-cache-arm64
      LUET_INSTALL_FROM_COS_REPO: false
    steps:
      - run: |
          sudo rm -rf build || true
          sudo rm -rf bin || true
          sudo rm /usr/bin/luet || true
          sudo rm -Rf /etc/luet/ || true
          sudo rm -Rf /var/tmp/luet || true
          sudo rm -Rf /var/luet || true
      - name: Install Go
        run: |
          curl -L https://golang.org/dl/go1.16.5.linux-arm64.tar.gz -o go1.16.5.linux-arm64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.5.linux-arm64.tar.gz
      - name: Install make
        run: |
            sudo apt-get update
            sudo apt-get install -y make
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install --no-spinner -y toolchain/yq
      - name: Run make validate
        run: |
          sudo -E make validate
      - name: Build packages ðŸ”§
        run: |
          export PATH=$PATH:/usr/local/go/bin
          mkdir build || true
          pushd ./.github
          go build -o build
          popd
          ./.github/build
          ls -liah $PWD/build
          sudo chmod -R 777 $PWD/build
      - name: Run make create-repo
        run: |
          sudo -E make create-repo
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: build-green-arm64
          path: build
          if-no-files-found: error
