name: Build cOS Pull requests - docker-orange-x86_64
on: 
 pull_request:
   paths:
     - conf/**
     - packages/**
     - make/**
     - .github/**
     - Makefile
     - tests/**
concurrency:
  group: ci-Pull requests - docker-orange-x86_64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  docker-build-orange:
    runs-on: ubuntu-latest
    env:
      FLAVOR: orange
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Build  ðŸ”§
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source .envrc
          cos-build $FLAVOR
