name: Build cOS nightly-orange-x86_64
on: 
 schedule:
   - cron: 0 20 * * *
concurrency:
  group: ci-nightly-orange-x86_64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  docker-build-orange:
    runs-on: ubuntu-latest
    env:
      FLAVOR: orange
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Build  ðŸ”§
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source .envrc
          cos-build $FLAVOR
  build-orange-x86_64:
    runs-on: ubuntu-latest
    env:
      LUET_ARCH: x86_64
      FLAVOR: orange
      ARCH: x86_64
      FINAL_REPO: quay.io/costoolkit/releases-orange
      DOWNLOAD_METADATA: false
      PUSH_CACHE: false
      REPO_CACHE: quay.io/costoolkit/build-orange-cache
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install --no-spinner -y toolchain/yq
      - name: Run make validate
        run: |
          sudo -E make validate
      - name: Build packages ðŸ”§
        run: |
          export PATH=$PATH:/usr/local/go/bin
          mkdir build || true
          pushd ./.github
          go build -o build
          popd
          sudo -E ./.github/build
          ls -liah $PWD/build
          sudo chmod -R 777 $PWD/build
      - name: Run make create-repo
        run: |
          sudo -E make create-repo
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: build-orange-x86_64
          path: build
          if-no-files-found: error
  raw-images-orange:
    runs-on: ubuntu-latest
    container: opensuse/leap:15.3
    needs:
    - build-orange-x86_64
    steps:
      - name: Install OS deps
        run: |
          zypper in -y bc qemu-tools sudo curl e2fsprogs dosfstools mtools squashfs gptfdisk make tar gzip xz which
      - uses: actions/checkout@v2
      - name: Download result for build
        uses: actions/download-artifact@v2
        with:
          name: build-orange-x86_64
          path: build
      - name: Install toolchain
        run: |
          # Since some time /var/lock is a symlink to /run/lock, which doesn't exit in the continer
          rm -rf /var/lock
          mkdir -p /var/lock
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install --no-spinner -y toolchain/yq
      - name: Export cos version
        run: |
             source .github/helpers.sh
             echo "COS_VERSION=$(cos_version)" >> $GITHUB_ENV
      - name: Run make raw_disk
        run: |
          sudo -E make raw_disk
      - name: Run make azure_disk
        run: |
          sudo -E make azure_disk
      - name: Run make gce_disk
        run: |
          sudo -E make gce_disk
      - name: Rename images
        run: |
          mv disk.raw cOS-Vanilla-RAW-orange-${{ env.COS_VERSION }}-x86_64.raw
          mv disk.vhd cOS-Vanilla-AZURE-orange-${{ env.COS_VERSION }}-x86_64.vhd
          mv disk.raw.tar.gz cOS-Vanilla-GCE-orange-${{ env.COS_VERSION }}-x86_64.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-Vanilla-RAW-orange-${{ env.COS_VERSION }}-x86_64
          path: |
            cOS-Vanilla-RAW-orange-${{ env.COS_VERSION }}-x86_64.raw
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-Vanilla-AZURE-orange-${{ env.COS_VERSION }}-x86_64
          path: |
            cOS-Vanilla-AZURE-orange-${{ env.COS_VERSION }}-x86_64.vhd
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-Vanilla-GCE-orange-${{ env.COS_VERSION }}-x86_64
          path: |
            cOS-Vanilla-GCE-orange-${{ env.COS_VERSION }}-x86_64.tar.gz
          if-no-files-found: error
  tests-raw-disk-deploy-orange:
    runs-on: macos-10.15
    needs: raw-images-orange
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - uses: actions/checkout@v2
      - name: Install deps
        run: brew install yq cdrtools
      - name: Export cos version
        run: |
          export YQ=/usr/local/bin/yq
          source .github/helpers.sh
          echo "COS_VERSION=$(cos_version)" >> $GITHUB_ENV
      - name: Download RAW image
        uses: actions/download-artifact@v2
        with:
          name: cOS-Vanilla-RAW-orange-${{ env.COS_VERSION }}-x86_64
      - name: Run tests ðŸ”§
        run: |
          export GOPATH="/Users/runner/go"
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          PATH=$PATH:$GOPATH/bin
          sudo -E make raw_disk_test_deploy
      - name: Change serial log ownership
        if: failure()
        run: |
          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          sudo chown $USER_ID:$GROUP_ID serial_port1.log
          sudo chmod 777 serial_port1.log
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cOS-raw_disk_test_deploy-orange.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cOS-raw_disk_test_deploy-orange.serial.zip
          path: serial_port1.log
          if-no-files-found: warn
