name: docker-teal-x86_64
on: 
 pull_request:
   paths:
     - conf/**
     - packages/**
     - make/**
     - .github/**
     - Makefile
     - tests/**
concurrency:
  group: ci-docker-teal-x86_64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
