name: iso
on:
  workflow_dispatch: # for triggering it manually

concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  iso:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
    #         - flavor: "fedora"
    #         - flavor: "ubuntu"
    steps:
      - name: Set pending
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'pending'
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          commit: ${{ github.sha }}
          name: build-${{ matrix.flavor }}
          path: build

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso squashfs-tools
          sudo -E make deps

      - name: Build ISO from local build ðŸ”§
        if: github.event_name != 'schedule' && !startsWith(github.ref, 'refs/tags/')
        run: |
          sudo -E make local-iso

      - name: Build ISO from remote repositories ðŸ”§
        if: github.event_name == 'schedule' || startsWith(github.ref, 'refs/tags/')
        run: |
          sudo -E make iso
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip
          path: |
            *.iso
            *.sha256
          if-no-files-found: error
      - name: Set success
        if: success()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'success'
      - name: Set failure
        if: failure()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'failure'
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

      - name: Run packer-qemu workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: packer-qemu
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Run packer-vbox workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: packer-vbox
          token: ${{ secrets.PERSONAL_TOKEN }}
