name: nightly

on:
  workflow_dispatch:
  schedule:
    # run at 02:30 UTC every night
    - cron:  '30 2 * * *'

jobs:
  build-matrix:
    strategy:
      matrix:
        arch: ['x86_64', 'aarch64']
        flavor: ['green', 'tumbleweed']
    uses: ./.github/workflows/build_and_test.yaml
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
