name: PR
on:
  pull_request:
    paths:
      - tests/**
      - make/**
      - Makefile
      - .github/**
      - pkg/**
      - cmd/**
      - go.mod
      - go.sum
      - examples/**

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      arch: ${{ steps.set-matrix.outputs.arch }}
      flavor: ${{ steps.set-matrix.outputs.flavor }}
    steps:
    - id: set-matrix
      run: |
        if [ "${{ contains(github.event.pull_request.labels.*.name, 'arm64') }}" == "true" ]; then
          echo "arch=['x86_64', 'aarch64']" >> $GITHUB_OUTPUT
        else
          echo "arch=['x86_64']" >> $GITHUB_OUTPUT
        fi
        if [ "${{ contains(github.event.pull_request.labels.*.name, 'all-distros') }}" == "true" ]; then
          echo "flavor=['green', 'tumbleweed', 'blue', 'orange']" >> $GITHUB_OUTPUT
        else
          echo "flavor=['green']" >> $GITHUB_OUTPUT
        fi

  build-matrix:
    needs: detect
    strategy:
      matrix:
        arch: ${{fromJson(needs.detect.outputs.arch)}}
        flavor: ${{fromJson(needs.detect.outputs.flavor)}}
        exclude:
          - arch: aarch64
            flavor: blue
          - arch: aarch64
            flavor: orange
      fail-fast: false
    uses: ./.github/workflows/build_and_test.yaml
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
